riscv-non-isa/riscv-asm-manual

riscv-asm.md

Initial commit transferring across the tables from the rv8 repo.

Add tables containing assembler directives and relocation expansions

---

riscv-asm.md

I don't think this syntax has been documented anywhere else.

Document how rounding modes can be specified, and the supported mnemonics

---

riscv-asm.md

Include table with most basic information on the registers of RV32I, with a basic skeleton for inclusion of floating point, control and vector registers. An alternative would be to only put RV32I here and include the other registers in separate chapters. Assumes that the use of `sp` and friends will be described in detail in later parts of the manual.
Signed-off-by: Scot W. Stevenson <scot.stevenson@gmail.com>

Added basic table and general comments on registers

---

riscv-asm.md

Hat tip to Andrew Waterman for clarifying that the 32-bit form of UNIMP is an alias for `CSRRW x0, cycle, x0`.
The explicit 16-bit form `C.UNIMP` isn't yet implemented in binutils. There's probably no point in indicating this in the document itself, as this will probably change soon.

Add description of UNIMP pseudo-instruction

---

riscv-asm.md

The example output in the section on Relative addressing didn't match the input & the target offsets looked wrong too.

Make relative addressing section reg names match

---

riscv-asm.md

Clarify how both implicit and explicit operands are used.

riscv-asm.md: clarify globals and calls

---

riscv-asm.md

Seems like privileged spec URL is no longer working and is listed in the same page with User Level specification

Remove broken link

---

riscv-asm.md

Add `sext.b`, `sext.h`, `zext.b`, `zext.h` and `zext.w`, and mention `sext.b` and `sext.h` could be non pseudo instruction, the motivation is we already has `sext.w` now, and B ext also want to define more pseudo for `sext` or `zext`, so why not add to the baseline pseudo instruction, and let assembler pick best way to expand.

Add pseudoinstruction: sext.b, sext.h, zext.b, zext.h and zext.w

---

riscv-asm.md

My (mis)reading of the ISA manual leads me to expect `c.lui` to accept a nonzero integer immediate in the interval [-32, 31]. The GNU assembler rejects values in [-32, -1]. This PR aims to clear up this behavior I found counterintuitive. 
EDIT: Writing in a hurry, I originally worded this more strongly than I meant. GAS's behavior is actually rather reasonable.

Document (c)lui immediate

---

riscv-asm.md

`[^1]` and `[^2]` first appear in *Load and Store Global* section. Without this PR, GitHub ignores lines 484 and 485 and links the reference at line 479 and 480 to that section, which is confusing. This PR fixes the footnote numbering.

Fix footnote numbering

---

riscv-asm.md

The RISC-V assembly language allows negative `addi` immediates to be expressed in more than one way, which may be surprising to newcomers. This PR is intended to resolve riscv-non-isa/riscv-asm-manual#70.

Document addi immediate

---

riscv-asm.md

Changes:
- 2021/8/12:
- Add , after arch.
- Only allow enable/disable one arch one time.
- Add = operator to set arch to specific configuration.
- 2021/7/29: Extend `.option` rather than `.push_arch`/`.pop_arch`.
------
This commit extend .option diretive with new keyword:
- .option arch <ext-list>
Enable and/or disable specific ISA extensions for following code regions, but 
without changing the arch attribute, that means it won't raise the minimal
execution environment requirement, so the user should take care to protect
execution of the code regions around `.option push`/`.option arch`/`.option pop`.
A typical use case is is with `ifunc`, e.g. the libc is built with `rv64gc`,
but a few functions like memcpy provide two versions, one built with `rv64gc`
and one built with `rv64gcv`, and …

Proposal:  Extend .option directive for control enabled extensions on specific code region

---

riscv-asm.md

Describe the scope of this document, my expection to this document can become kind of offical RISC-V standard Assembly manual, but this doucment apparently still need lots polish...
So limited the scope to the open source toolchain for GNU and LLVM compiler.

Add scope section

---

riscv-asm.md

Split from #85, this PR only contain non-zfa part.
Contain two things:
1. `.float` and `.double`
2. Generic way to to load a floating point immediate to floating point register via load from memeory.

Document floating point directive and generic way to to load a floating point immediate to floating point register

---

riscv-asm.md

Split non-zfa part into https://github.com/riscv-non-isa/riscv-asm-manual/pull/86
This is chaining PR with #86
---
Zfa has provide fli instruction to load a floating point immediate, but some of value are hard to written by human, so we would like to support 3 different format of floating value: hexadecimal, decimal, or standard notation formats (a.k.a scientific notation); document this could let user easier know how to use those value in their asm code.

Document fli instruction from zfa extension

---

riscv-asm.md

We provide a range of pseudoinstructions to access globals. Currently only the signed loads/stores are listed. Let's add the unsigned accesses as well.
Fixes #94.

Adding unsigned load/stores

---

riscv-asm.md

Fixed the two issues reported in issue #98:
1. For pseudo instructions that map to more than one real instruction, placed the real instructions on separate lines
2. Added a footnote about 'myriad sequences' expression

Fixed issue #98

---

riscv-asm.md

Move the `.p2align` and `.balign` directives next to `.align` in the table, and add a note recommending avoiding `.align` in favour of the explicit directives which are much clearer.

Recommend avoiding .align

---

riscv-asm.md

This change is to make `tail` conform with software guarded jump of [Zicfilp]. The reason to not choose `t1` as the label register is that `t1` is also as `.got.plt` offset of `_dl_runtime_resolve` in [PLT].
[Zicfilp]: https://github.com/riscv/riscv-cfi/blob/main/cfi_forward.adoc
[PLT]: https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-elf.adoc#procedure-linkage-table

Change scratch register of tail to t2 when Zicfilp enabled.

---

src/asm-manual.adoc

Add .insn directive with brief description and link to full documentation.
Co-developed-by: Tim Hutt <timothy.hutt@codasip.com>
Co-developed-by: Christoph Müllner <christoph.muellner@vrull.eu>

Add .insn directive

---

.github/workflows/build-doc.yml
src/preamble.adoc

Address https://github.com/riscv-non-isa/riscv-asm-manual/issues/112
- Add CI workflow to create PDF/HTML and draft release for every push to main
- improve PDF content layout
See here how it looks like: https://github.com/axel-h/riscv-asm-manual/releases

Add CI workflow to create PDF/HTML

---

src/asm-manual.adoc

Closes #110 .
Preview: [riscv-asm.pdf](https://github.com/user-attachments/files/17522971/riscv-asm.pdf)

Add V extension pseudoinstructions

---

src/asm-manual.adoc

During the latest Toolchain SIG meeting it was raised that this section does not make its intent and behavior clear enough. This rewords the prose to explain what is going on in more detail.

Rewrite the far branches section

---

src/asm-manual.adoc

Those two pseudo-instructions are trivial and also already implemented in the
binutils[1] and LLVM[2].
[1] https://github.com/bminor/binutils-gdb/commit/e23eba971dd409b999dd83d8df0f842680c1c642
[2] https://github.com/llvm/llvm-project/commit/84080793c56558b6e677fa70577e87e2e8404816
NOTE: bintuils supports those 2 kind of pseudo-instructions since RISC-V support began.
---
Also come with 2 small patch for tweak the document:
- `Add .h variant of floating point pesudo instructions`
- `Use fr[ds] for FPR to prevent confuse with GPR for floating point pesudo instructions`

Add fgt.[hsd] and fge.[hsd] pseudo-instructions

---

src/asm-manual.adoc

The existing documentation didn't mention that `ld` and `sd` symbol pseudos aren't available on RV32. This change clarifies that these are available, but denote pair load/stores using the Zilsd instructions.

[Zilsd] Clarify Symbol Pseudos for Zilsd

---

src/asm-manual.adoc

to pseudo instructions table.
Removed a redundant string from pseudo instruction table.
Fix issue #133
Fix issue #134

Added 'jump offset, rt' and 'call rt, offset'

---

src/asm-manual.adoc

-Fix objdump option for printing numeric register names.
-Add more Zfhmin pseudoinstructions.

Add Floating Point registers.
